# intro to tensors

In [69]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)


2.18.0


## `tf.constant`

In [70]:
# creating tensors with tf.constant()
# create a constant tensor from a tensor-like object
scalar =  tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [71]:
# check the number of dimensions of a tensor (ndim is the number opf dimensions)
scalar.ndim

0

In [72]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [73]:
# check dimension of our vector
vector.ndim

1

In [74]:
# create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]] )
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [75]:
matrix.ndim

2

In [76]:
# another matrix
another_matrix = tf.constant([
                                [10., 7.], 
                                [3., 2.],
                                [8., 9.]
                            ], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [77]:
another_matrix.ndim

2

In [78]:
# create a tensor
tensor = tf.constant([
                        [
                            [1, 2, 3],
                            [4, 5, 6]
                        ],
                        [
                            [7, 8, 9],
                            [10, 11, 12]
                        ],
                        [
                            [13, 14, 15],
                            [16, 17, 18]
                        ]
                    ])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [79]:
tensor.ndim

3

## `tf.Variable`

In [80]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [81]:
changeable_tensor = tf.Variable([15, 5])
unchangeable_tensor = tf.constant([15, 5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([15,  5], dtype=int32)>)

In [82]:
# changeable_tensor.ndim

In [83]:
# change elements
changeable_tensor[0].assign(20)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([20,  5], dtype=int32)>

# random tensors

sTensors of some arbirary size which contains random numbers

Useful to initialise the patterns/weights - then values are adjusted as model is trained


In [84]:
random_1 = tf.random.Generator.from_seed(42)
random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2.normal(shape=(3, 2))

# are they equal
random_1, random_2, random_1 == random_2


(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7fb052b635d0>,
 False)

In [85]:
print(random_1.normal(shape=[3, 2]))

tf.Tensor(
[[ 0.17522676  0.71105534]
 [ 0.54882437  0.14896014]
 [-0.54757965  0.61634356]], shape=(3, 2), dtype=float32)


In [86]:
print(random_2.normal(shape=[3, 2]))

tf.Tensor(
[[ 0.17522676  0.71105534]
 [ 0.54882437  0.14896014]
 [-0.54757965  0.61634356]], shape=(3, 2), dtype=float32)


In [87]:
random_1 == random_2

False

## shuffle the order of elements in a tensor
Valuable when you want to shuffle your data so the inherent order doesn't affect learning

In [88]:
not_shuffled = tf.constant([
                                [10, 7],
                                [3, 4],
                                [2, 5]
])
not_shuffled



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [89]:
not_shuffled.ndim


2

In [90]:
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## create a tensor of all '1's

In [91]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

## create a tensor of all '1's

In [92]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## convert nump arrays into tensors

the main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing)

### convert NumPy arrays into tensors

In [93]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 & 25

numpy_A

# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [94]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [95]:
A.ndim

2

## get info from tensors
- #### shape
    - length (number of elements) of each of the dimension of a tensor
    - `tensor.shape`
- #### rank
    - the number of tensor dimensions. a scalar has rank 0, a vector has rank 1, a metrix is rank 2, a tensor has rank $n$
    - `tensor.ndim`
- #### axis or dimension
    - a particular dimension of a tensor
    - `tensor[0]. tensor[:, 1]_`
- #### size
    - the total number of items in the tensor
    - `tf.size(tensor)`
 

In [96]:
# create a rank 4 tensor (4 dimensions)
# rank_4_tensor = tf.ones(shape=(2, 5, 3, 9))
rank_4_tensor = tf.zeros(shape=(2, 5, 3, 9))
rank_4_tensor

<tf.Tensor: shape=(2, 5, 3, 9), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0

In [97]:
rank_4_tensor[0]

<tf.Tensor: shape=(5, 3, 9), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [98]:
# create 4-d tensor of random numbers
rank_4_random = tf.random.Generator.from_seed(42)
rank_4_random.normal(shape=(3, 2, 4, 6))

<tf.Tensor: shape=(3, 2, 4, 6), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ,
          -0.23193763, -1.8107855 ],
         [ 0.09988727, -0.50998646, -0.7535805 , -0.57166284,
           0.1480774 , -0.23362993],
         [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,
           1.6874489 , -0.4462975 ],
         [-2.3410842 ,  0.99009085, -0.0876323 , -0.635568  ,
          -0.6161736 , -1.9441465 ]],

        [[-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ,
          -1.5184573 , -0.4585211 ],
         [ 0.5714663 , -1.5331722 ,  0.45331386,  1.1487608 ,
          -1.2659091 , -0.47450137],
         [ 2.006022  ,  0.28288034, -0.30288252, -1.443651  ,
           1.0034493 ,  0.20857747],
         [ 0.35700995,  1.0648885 ,  1.2432485 , -2.2173238 ,
           0.18706243,  0.6617961 ]]],


       [[[ 0.01380118, -0.24827152,  1.2111493 , -0.7199124 ,
          -0.04082382,  2.6791053 ],
         [ 1.0914806 ,  0.33149615, -0.67958915, 

### tensor info

In [99]:
# get tensor info
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 5, 3, 9]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=270>)

## get various attributes of a tensor

In [100]:
print("Data type of every element", rank_4_tensor.dtype)
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of tensor", rank_4_tensor.shape)
print("Elements along the 0 axis", rank_4_tensor.shape[0])
print("Elements along the last axis", rank_4_tensor.shape[-1])
print("Total number of elements", tf.size(rank_4_tensor))
print("Total number of elements (NumPy)", tf.size(rank_4_tensor).numpy())
     

Data type of every element <dtype: 'float32'>
Number of dimensions (rank) 4
Shape of tensor (2, 5, 3, 9)
Elements along the 0 axis 2
Elements along the last axis 9
Total number of elements tf.Tensor(270, shape=(), dtype=int32)
Total number of elements (NumPy) 270


# indexing tensors
Tensors can be indexed just like python lists

In [101]:
### get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [102]:
### get the first elements of each dimension except for the final one
rank_4_tensor[:1, :1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 9), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [103]:
# create a rank 2 tensor
rank_2_tensor = tf.constant([
                                [10, 7],
                                [3, 4]
])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [104]:
some_list=[1, 2, 3, 4]
some_list[-1]

4

In [105]:
# get last temn of each row of rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

## add dimension - METHOD 1

In [106]:
# add dimension - METHOD 1
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor.ndim
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## add dimension - METHOD 2

In [107]:
# add dimension - METHOD 2
rank_3_tensor_1 = tf.expand_dims(rank_2_tensor, axis=1) # -1 means expand the final axis
print(rank_3_tensor_1.ndim)
print(rank_3_tensor_1)

3
tf.Tensor(
[[[10  7]]

 [[ 3  4]]], shape=(2, 1, 2), dtype=int32)


In [108]:
print("Data type of every element", rank_3_tensor_1.dtype)
print("Number of dimensions (rank)", rank_3_tensor_1.ndim)
print("Shape of tensor", rank_3_tensor_1.shape)
print("Elements along the 0 axis", rank_3_tensor_1.shape[0])
print("Elements along the last axis", rank_3_tensor_1.shape[-1])
print("Total number of elements", tf.size(rank_3_tensor_1))
print("Total number of elements (NumPy)", tf.size(rank_3_tensor_1).numpy())

Data type of every element <dtype: 'int32'>
Number of dimensions (rank) 3
Shape of tensor (2, 1, 2)
Elements along the 0 axis 2
Elements along the last axis 2
Total number of elements tf.Tensor(4, shape=(), dtype=int32)
Total number of elements (NumPy) 4


# manipulating tensors (Tensor Operations)
**Basic Operations**
+, -, *, /


In [109]:
# addition
tensor = tf.constant([[10, 7],
                      [3, 4]])
print("operation", tensor * 10)
print("orig", tensor)

tensor_add = tensor + 10
print(tensor_add)

operation tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
orig tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


### tenserflow functions

In [110]:
tf.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

# matrix multiplication
one of most common tensor operations

In [111]:
# in tensor flow
print(tensor)
tf.matmul(tensor, tensor)


tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [112]:
tensor @ tensor  # using pythonmatrix ultiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [113]:
mat_1 = tf.constant([
    [1, 2, 5],
    [7, 2, 1],
    [3, 3, 3]
])
mat_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [114]:
mat_2 = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])
mat_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [115]:
tf.matmul(mat_1, mat_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [116]:
X = tf.constant([
    [1, 2],
    [3, 3],
    [5, 6]
])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 3],
       [5, 6]], dtype=int32)>

In [117]:
Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [118]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 51,  57,  63],
       [ 95, 106, 117]], dtype=int32)>

In [119]:
# change the shape of Y
Y.shape, X.shape
print(Y)

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [120]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [121]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 51,  57,  63],
       [ 95, 106, 117]], dtype=int32)>

In [122]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [107, 118]], dtype=int32)>

# dot product

In [123]:
# perform do product on X and Y (requires X or Y to be transposed)
print(X)
print(Y)

tf.Tensor(
[[1 2]
 [3 3]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [124]:
# perform do product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [107, 118]], dtype=int32)>

In [125]:
# perform matrix multiplication between X & Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 45,  57,  69],
       [ 83, 105, 127]], dtype=int32)>

In [126]:
# perform matrix multiplication between X & Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 51,  57,  63],
       [ 95, 106, 117]], dtype=int32)>

In [127]:
# check the values of Y, reshaoe Y and transpose Y
print("normal Y:", Y)
print("transposed Y:", tf.transpose(Y))
print("reshaped Y:", tf.reshape(Y, shape=(2,3)))


normal Y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
transposed Y: tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
reshaped Y: tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


### change datatype of a tensor


In [128]:
tf.__version__

'2.18.0'

In [129]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [130]:
C = tf.constant([1, 7])
C.dtype

tf.int32

In [131]:
# change from float32 float16
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [132]:
# change from inti32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [133]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>

### aggregating

Aggregating tensors = condensing them from multiple values down to a smaller amount of values


In [134]:
# get absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [135]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of aggegation
* minimum
* maximumm
* mean of a tensor
* sum of a tensor

In [136]:
agg_1 = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
agg_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [137]:
agg_2 = tf.constant([
    [10, 11, 16],
    [12, 13, 17],
    [14, 15, 18]
])
agg_2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 11, 16],
       [12, 13, 17],
       [14, 15, 18]], dtype=int32)>

In [138]:
print("min", tf.minimum(agg_1, agg_2))
print("max", tf.maximum(agg_1, agg_2))
print("mean_1", tf.reduce_mean(agg_1))
print("mean_2", tf.reduce_mean(agg_2))
print("sum_1", tf.reduce_sum(agg_1))
print("sum_2", tf.reduce_sum(agg_2))


min tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
max tf.Tensor(
[[10 11 16]
 [12 13 17]
 [14 15 18]], shape=(3, 3), dtype=int32)
mean_1 tf.Tensor(5, shape=(), dtype=int32)
mean_2 tf.Tensor(14, shape=(), dtype=int32)
sum_1 tf.Tensor(45, shape=(), dtype=int32)
sum_2 tf.Tensor(126, shape=(), dtype=int32)


In [139]:
E =  tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([45, 83, 48, 82, 22, 57, 48,  1, 36, 17,  7, 29, 50, 13, 72, 97, 22,
       92, 49, 48, 79,  2, 79, 50, 64, 96, 79, 79, 98, 96, 48, 30, 64, 25,
       20, 99, 97, 96, 95, 64, 54, 11, 25, 80, 81, 42, 13, 16, 22,  9])>

In [140]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [141]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [142]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [143]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [144]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2631>

In [145]:
import tensorflow_probability as tfp
tfp.stats.variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=955.515625>

In [146]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.911415100097656>

# positional parameters

In [147]:
# new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [148]:
# Find the positional maximum
pos_max = tf.argmax(F)
pos_max

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [149]:
# index on out largest value position
val_max = F[tf.argmax(F)]
val_max

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [150]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [151]:
# find the positional minimum
pos_min = tf.argmin(F)
pos_min

val_min = F[tf.argmin(F)]
val_min


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

## squeezing a tensor (removing all single dimensions)

In [152]:
# create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [153]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [154]:
# remove dimensions of size 1 from the shape of a tensor
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# one-hot encoding

In [161]:
# creare a list of indices
some_list = [0, 1, 2, 3] # i.e could be red, gree, blue. purple

# one hot encode list of indices
depth = 4
one_hot_lst = tf.one_hot(some_list, depth)

one_hot_lst


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [163]:
# specify custome values for one-hot
oh_lst = tf.one_hot(some_list, depth, on_value="havana banana", off_value="arjuna")
oh_lst

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'havana banana', b'arjuna', b'arjuna', b'arjuna'],
       [b'arjuna', b'havana banana', b'arjuna', b'arjuna'],
       [b'arjuna', b'arjuna', b'havana banana', b'arjuna'],
       [b'arjuna', b'arjuna', b'arjuna', b'havana banana']], dtype=object)>

## squaring; log; square root

In [178]:
tf.random.set_seed(42)
# H = tf.constant(tf.random.uniform(shape=[50]))
H = tf.range(1, 10)
H


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [179]:
# square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [184]:
# log
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [185]:
# square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

# tensors with NumPy

In [187]:
# reate a tensor directly fromma NumPy array

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [188]:
# convert tensor a to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [191]:
J_array = np.array(J)
print(J_array, type(J_array))

[ 3.  7. 10.] <class 'numpy.ndarray'>


In [198]:
# default types of each slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

print("numpy_J", numpy_J)
print("tensor_J", tensor_J)

print(numpy_J.dtype, tensor_J.dtype)


numpy_J tf.Tensor([ 3.  7. 10.], shape=(3,), dtype=float64)
tensor_J tf.Tensor([ 3.  7. 10.], shape=(3,), dtype=float32)
<dtype: 'float64'> <dtype: 'float32'>
